CREATE TABLE `e70_tests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`testDate` varchar(10) NOT NULL,
	`nozzleId` int NOT NULL,
	`nozzleLabel` varchar(64),
	`fuelType` enum('petrol','diesel') NOT NULL,
	`meterReadingBefore` decimal(12,3),
	`meterReadingAfter` decimal(12,3),
	`drawnQty` decimal(8,3) NOT NULL,
	`returnedQty` decimal(8,3) DEFAULT '0',
	`netDeduction` decimal(8,3),
	`densityReading` decimal(8,4),
	`colourObservation` varchar(128),
	`result` enum('pass','fail','observation') NOT NULL DEFAULT 'pass',
	`observations` text,
	`testedBy` int,
	`testedByName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `e70_tests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fuel_deliveries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deliveryDate` varchar(10) NOT NULL,
	`deliveryTime` varchar(8),
	`invoiceNumber` varchar(128),
	`supplierName` varchar(255),
	`vehicleNumber` varchar(32),
	`driverName` varchar(255),
	`fuelType` enum('petrol','diesel','lubricant') NOT NULL,
	`orderedQty` decimal(10,3),
	`deliveredQty` decimal(10,3),
	`unloadedQty` decimal(10,3),
	`invoiceRate` decimal(10,4),
	`invoiceAmount` decimal(14,2),
	`status` enum('pending_qc','qc_passed','qc_failed','unloaded','rejected') NOT NULL DEFAULT 'pending_qc',
	`scannedReceiptId` int,
	`loggedBy` int,
	`loggedByName` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fuel_deliveries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fuel_delivery_quality_checks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deliveryId` int NOT NULL,
	`checkedAt` timestamp NOT NULL DEFAULT (now()),
	`checkedBy` int,
	`checkedByName` varchar(255),
	`densityReading` decimal(8,4),
	`densityPass` tinyint,
	`colourCheck` enum('clear','yellow','amber','contaminated'),
	`colourPass` tinyint,
	`waterContamination` tinyint,
	`sedimentCheck` tinyint,
	`sealIntact` tinyint,
	`documentMatch` tinyint,
	`dipstickReading` decimal(10,3),
	`overallResult` enum('pass','fail','conditional') NOT NULL,
	`remarks` text,
	`decision` enum('approve_unload','reject_tanker','pending') NOT NULL DEFAULT 'pending',
	`decisionAt` timestamp,
	`decisionRemarks` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `fuel_delivery_quality_checks_id` PRIMARY KEY(`id`)
);
